<IntroScreen>:
    FloatLayout:
        id: stars

    BetterFloatLayout:
        id: meteor

    FloatLayout:
        id: ship

    FloatLayout:
        id: tint


<CrashScreen>:
    FloatLayout:
        id: stars

    FloatLayout:
        id: canyon

    BetterFloatLayout:
        id: guide

        Image:
            source: "textures/guide/intro.png"
            size: root.size



<BaseBuildScreen>: